### ISSUE TITLE
please provide Arduino code.

### ISSUE THREAD

**Issue by harshalpowankar12** [petar-prog91/android-bluetooth-led-rgb-controller#1]

**Comment by Chirag-01** [comment]
@harshalpowankar12 Did you got Aruino Code Please share It if possible...

**Comment by harshalpowankar12** [comment]
I don't have an Arduino code Brother.

**Comment by Chirag-01** [comment]
@harshalpowankar12 What should we do now I need it for my project and I have no idea about this

**Comment by Chirag-01** [comment]
@petar-prog91 Sir please Share Arduino code

**Comment by petar-prog91** [comment]
Here you go guys, I'm not sure if this will help you, I don't remember if this was the latest working version I had, you'll have to debug it yourself:

#include <SoftwareSerial.h>                     
#include <EEPROM.h>

SoftwareSerial mySerial(2, 4); // RX, TX


int mRed = 0;
int mGreen = 1;
int mBlue = 2; 
  
/* clap sound on/off */

int clapInput = 0;
int clapValue=0;
boolean clapped = false;

/* LED strip */

int blue= 11;
int red= 10;
int green = 9;
bool ledStripState = false; // on == true; off == false;

/* Bluetooth serial comm. */

char character;
String command;

/* User Functions */

void ledStripOn();
void ledOldColor();
void ledStripOff();

void clapToStart(){
  clapValue= analogRead(clapInput);

  if (clapValue >= 550){
      clapped=true;
      delay(200);
      
        if(!ledStripState){
            ledStripOn();
            delay(5);
            ledOldColor();
        }
        
        else {
            ledStripOff();
        }
              
      ledStripState=!ledStripState;
        clapped=false;
    }
}

void commWithBT(){
    
    while(mySerial.available() > 0) {
      character = mySerial.read(); 
      command.concat(character); 
        delay (1);
    }

    if(command == "LED_ON")
    {
      ledStripOn();
      ledOldColor();
      ledStripState = true;
    }
    
    else if(command == "LED_OFF")
    {
      ledStripOff();
      ledStripState = false;
    }
   
    else if (command[0] == 'R') { 
      command = command.substring(0, 5);        
      int value = command.substring(2).toInt();  
      
      analogWrite(red, value);
      EEPROM.write(mRed, value);
    }

    else if (command[0] == 'G') {
      command = command.substring(0, 5);
      int value = command.substring(2).toInt();
      
      analogWrite(green, value);
      EEPROM.write(mGreen, value);
    }

    else if (command[0] == 'B') {
      command = command.substring(0, 5);
      int value = command.substring(2).toInt();
      
      analogWrite(blue, value);
      EEPROM.write(mBlue, value);
    }
      
    command = ""; 
 }

void ledStripOn(){
  digitalWrite(red, HIGH);
  digitalWrite(green, HIGH);
  digitalWrite(blue, HIGH);
}
 
void ledStripOff(){
  digitalWrite(green, LOW);
  digitalWrite(blue, LOW);
  digitalWrite(red, LOW);
}

void ledOldColor() {
  int valueRed = EEPROM.read(mRed);
  analogWrite(red, valueRed);
  
  int valueGreen = EEPROM.read(mGreen);
  analogWrite(green, valueGreen);
  
  int valueBlue = EEPROM.read(mBlue);
  analogWrite(blue, valueBlue);
}

void setup() {
  Serial.begin(9600);
   
  pinMode(clapInput, INPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
  
  mySerial.begin(9600);
}

void loop() {
  
  clapToStart();
  if (mySerial.available() > 0) {
    commWithBT();
  }
  
}

**Comment by petar-prog91** [comment]
Or if it's easier for you I've added it in repo:
https://github.com/petar-prog91/android-bluetooth-led-rgb-controller/blob/master/arduino.ino

**Comment by Chirag-01** [comment]
@petar-prog91  Thank you for the code !!
